#Autogenerated by ReportLab guiedit do not edit
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin, Path, ArcPath, String, Line
from reportlab.lib.colors import red, black, gray, silver,PCMYKColor,toColor

class CO2(_DrawingEditorMixin,Drawing):
    def __init__(self,width=200,height=200,*args,**kw):
        Drawing.__init__(self,width,height,*args,**kw)
        self.width       = 400
        self.height       = 200
        self._add(self,Path(),name='co2path',validate=None,desc=None)
        self._add(self,ArcPath(),name='cloud',validate=None,desc=None)
        self.co2path.strokeWidth = 3
        self.co2path.strokeColor      = toColor(PCMYKColor(72,62,43,37))
        self.co2path.strokeLineCap    = 1
        #Draw C
        self.co2path.moveTo(60,50)
        self.co2path.lineTo(42,50)
        self.co2path.lineTo(42,10)
        self.co2path.lineTo(60,10)
        #Draw 0
        self.co2path.moveTo(70,10)
        self.co2path.lineTo(90,10)
        self.co2path.lineTo(90,50)
        self.co2path.lineTo(70,50)
        self.co2path.lineTo(70,10)
        # Draw 2
        self.co2path.moveTo(100,26)
        self.co2path.lineTo(110,26)
        self.co2path.lineTo(110,18)
        self.co2path.lineTo(100,18)
        self.co2path.lineTo(100,10)
        self.co2path.lineTo(110,10)
        #Draw Cloud Arcs
        #P = getArcPoints(centerx, centery, radius, startangledegrees, endangledegrees, yradius=yradius, degreedelta=degreedelta, reverse=reverse)
        self.cloud.fillColor = None
        self.cloud.strokeWidth = 3
        self.cloud.strokeColor      = toColor(PCMYKColor(72,62,43,37))
        #self.cloud.moveTo()
        self.cloud.addArc(30,60,25,35,270,reverse=0)
        self.cloud.moveTo(40,82)
        self.cloud.addArc(65,90,26,0,180,reverse=1)
        self.cloud.moveTo(91.0, 90.0)
        self.cloud.addArc(118,80,26,270,170,reverse=1)
        # Draw NOW Underline
        self._add(self,Line(0,0,10,10),name='grayline',validate=None,desc=None)
        self.grayline.strokeWidth      = 3
        self.grayline.x1               = 190
        self.grayline.strokeColor      = toColor(PCMYKColor(16,11,11,0))
        self.grayline.x2               = 140
        self.grayline.y1               = 10
        self.grayline.x2               = 138
        self.grayline.x1               = 192
        #Draw "NOW" String
        self._add(self,String(10,10,'text'),name='now',validate=None,desc=None)
        self.now.x          = 140
        self.now.y          = 15
        self.now.fontSize   = 40
        self.now.text       = 'NOW'
        self.now.fontSize   = 23
        self.now.x          = 138
        self.now.fontName   = 'Helvetica'
        self.now.x          = 137
        self.now.fontSize   = 22
        self.now.y          = 20
        self.width       = 200
        self.height      = 130

if __name__=="__main__": #NORUNTESTS
    CO2().save(formats=['pdf'],outDir='.',fnRoot=None)
