#Autogenerated by ReportLab guiedit do not edit
#from reportlab import xrange
from reportlab.graphics.charts.legends import Legend
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.shapes import Drawing, _DrawingEditorMixin
from reportlab.lib.colors import PCMYKColor, Color
from utils import registerFonts

class InvestorCompanySectorsPie(_DrawingEditorMixin,Drawing):
	def __init__(self,width=400,height=200,*args,**kw):
		Drawing.__init__(self,width,height,*args,**kw)
		registerFonts()
		self.height      = 184
		self.width       = 200
		self._add(self,Pie(),name='chart',validate=None,desc=None)
		self.chart.width               = 110
		self.chart.height              = 110
		self.chart.y                   = self.height - self.chart.height- 10
		self.chart.x                   = 0.5*(self.width - self.chart.width)
		self._add(self,Legend(),name='legend',validate=None,desc=None)
		self.legend.boxAnchor        = 's'
		self.legend.dividerLines     = 1|2|4
		self.legend.dividerOffsY     = 6
		self.legend.x                = self.width*0.5
		self._colors = [PCMYKColor(30.47,23.44,15.23,53.52),PCMYKColor(69.92,52.34,1.17,12.5), PCMYKColor(91.02,75.52,61.72,97.27), PCMYKColor(39.84,0,0,0), PCMYKColor(68.75,51.56,1.17,12.11), PCMYKColor(19.92,0,0,0), PCMYKColor(79.69,59.77,1.56,14.06), PCMYKColor(69.92,23.05,1.17,12.5),]
		self._labels = ['Leisure and Hospitality','Construction']
		self._data   = [0.3438,0.6562]
		self.legend.y                = 10
		self.legend.strokeWidth      = 0
		self.legend.alignment='right'
		self.legend.fontSize         = 7
		self.legend.fontName         = 'MuseoSans_300'
		self.legend.dy               = 10
		self.legend.dx               = 10
		self.legend.deltay           = 10
		self.chart.slices.strokeWidth               = 0.5
		self.legend.autoXPadding     = 2
		self.legend.columnMaximum    = 4
		self.legend.dxTextSpace      = 2

	def getContents(self):
		chart = self.chart
		slices = chart.slices
		data = chart.data = self._data
		colors = self._colors
		labels = self._labels
		n = len(data)
		self.legend.colorNamePairs   = [(colors[i], (labels[i],"%8.2f%%  " % (100*data[i]))) for i in range(n)]
		for i in range(n): slices[i].fillColor = colors[i]
		return Drawing.getContents(self)

if __name__=="__main__": #NORUNTESTS
	InvestorCompanySectorsPie().save(formats=['pdf'],outDir='.',fnRoot=None)
